INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /api/v1/apilist
Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework_swagger/renderers.py", line 55, in render
    return render(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1023, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/urls.py changed, reloading.
WARNING:django.request:Not Found: /api/v1/users
WARNING:django.request:Forbidden: /api/v1/users/
WARNING:django.request:Forbidden: /api/v1/users/
WARNING:django.request:Forbidden: /api/v1/users/
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/urls.py changed, reloading.
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /api/v1/apilist
Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework_swagger/renderers.py", line 55, in render
    return render(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1023, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/serializers.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/users/
WARNING:django.request:Bad Request: /api/v1/login
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Forbidden: /api/v1/login
WARNING:django.request:Forbidden: /api/v1/login
WARNING:django.request:Forbidden: /api/v1/login
WARNING:django.request:Forbidden: /api/v1/login
WARNING:django.request:Forbidden: /api/v1/login
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Forbidden: /api/v1/login
WARNING:django.request:Forbidden: /api/v1/login
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Forbidden: /api/v1/login
ERROR:django.request:Internal Server Error: /api/v1/login
Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3ac1f1ba90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='%7byour-school%7d.thinkific.com', port=443): Max retries exceeded with url: /api/sso/v2/sso/jwt?jwt=%7Bpayload%7D&return_to=%7Burl%20to%20return%20to%7D&error_url=%7Burl%20to%20redirect%20to%20in%20the%20case%20of%20an%20error%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3ac1f1ba90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py", line 112, in post
    thinkific_token = requests.post(url, headers=headers)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/heaven/professional/impinge_office/SSO/env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='%7byour-school%7d.thinkific.com', port=443): Max retries exceeded with url: /api/sso/v2/sso/jwt?jwt=%7Bpayload%7D&return_to=%7Burl%20to%20return%20to%7D&error_url=%7Burl%20to%20redirect%20to%20in%20the%20case%20of%20an%20error%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3ac1f1ba90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/utils.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/utils.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/utils.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/utils.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Not Found: /api/v1/jwt=b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdF9uYW1lIjoiVGhpbmtpZmljIiwibGFzdF9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6InRoaW5raWZpY0B0aGlua2lmaWMuY29tIiwiaWF0IjoxNTIwODc1NzI1LCJleHRlcm5hbF9pZCI6InRoaW5raWZpY0B0aGlua2lmaWMuY29tIiwiYmlvIjoiTW9zdGx5IGhhcm1sZXNzIiwiY29tcGFueSI6IlRoaW5raWZpYyIsInRpbWV6b25lIjoiQW1lcmljYS9Mb3NfQW5nZWxlcyJ9.3fQvF3JJi1dAWcsGwTUwc-O36tmq2jIpl1IO3KYGRqI'
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Bad Request: /api/v1/login_thinkific
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Not Found: /api/v1/apilist/users/
WARNING:django.request:Not Found: /api/v1/apilist/users
WARNING:django.request:Not Found: /api/v1/apilist/users/
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/urls.py changed, reloading.
WARNING:django.request:Unauthorized: /api/v1/error
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
INFO:django.utils.autoreload:/home/heaven/professional/impinge_office/SSO/ssoproject/sso/views.py changed, reloading.
WARNING:django.request:Unauthorized: /api/v1/error
